import '/backend/assets/js/perfil/sidebar.js';
import '/backend/js/perfil/logout.js';
import '/backend/js/perfil/change-profile-pic.js';
import '/backend/js/perfil/bio.js';
import '/backend/js/perfil/avaliacoes.js';
import '/backend/js/perfil/experiencia.js';
import '/backend/js/perfil/disponibilidade.js';
import '/backend/js/perfil/conta.js';
import '/backend/js/perfil/suporte.js';